#!/usr/bin/bash
home=$(pwd)
for chem in $(find ./ -name chemshellout)
do
  dir=$(dirname $chem)
  cd $dir
    maxgrad=$(grep "Max grad" chemshellout|cat -n |tail -n 1|awk '{print $1,$4*27.2114/0.52}') 
    energy=$(grep "finished, energy" -i chemshellout|tail -n 1|awk '{print $5}') 
    if grep -q "finished, energy" -i chemshellout; then
    #  disp=" "
    #  for j in $(find ./ -name path_active.xyz)
    #  do
    #    disp=$disp" $(diffxyz $j $i 0 |sort -gk 4 |tail -n 1|awk '{print $5}')"
    #  done
      echo $dir $maxgrad $energy $disp
    fi
  cd $home
done
