#!/usr/bin/bash
for i in origin/chemshellout chemshellout
do
if [ -f $i ]; then
  echo $i $(grep "Max grad" $i|cat -n |tail -n 1|awk '{print $1,$4*27.2/0.52}') $(grep "finished, energy" -i $i|tail -n 1|awk '{print $5}')
fi
done

for i in path.xyz origin/path.xyz
do
  if [ -f $i ]; then
  for j in current.xyz origin/current.xyz
  do
  if [ -f $j ]; then
    echo $i $j $(diffxyz $j $i 0 |sort -gk 4 |tail -n 1)
fi
done
fi
done

