#!/bin/env bash
if [ $# -lt 1 ]; then
  echo "use origin as prefix"
  if [ -d origin ]; then
    mv origin origin0
  fi
  touch oo
  ls -d ./*/ |grep "\.\/origin" >oo
  if [ $(wc -l oo |awk '{print $1}') -gt 0 ]; then
    sed -i "s|./origin||g" oo
    sed -i "s|/| |g" oo
    startn=$(sort -n oo |tail -n 1)
    let "startn=startn+1"
    folder=origin$startn
    echo $folder
  else
    folder=origin0
  fi
  rm oo
else
  folder=$1
fi

mkdir $folder

rm *tmp* *_property.txt *.prop path_force.xyz
for i in $(ls dlf*  job.sh  *orca*  path*xyz chemshellout  opt.chm  *.gbw  *.pun gulp* pointcharges.xyz  slurm* *.ff)
do
mv $i $folder
done


for i in orca1.gbw ecpfile *.ff job.sh 
do
  if [ -f $folder/$i ]; then
    mv $folder/$i .
  fi
done
cp $folder/opt.chm .
result=$(grep "set result_pun" opt.chm|awk '{print $3}')
cp $folder/${result} ${folder}.pun

sed -i "/set coords/d" opt.chm #perfect-4pot.pun
sed -i "/set result_pun/d" opt.chm
sed -i "1s/^/set coords ${folder}.pun\n/" opt.chm
sed -i "1s/^/set result_pun conti-${folder}.pun\n/" opt.chm
