#!/bin/env bash
file=$1
out=$2

if [ ! -f $1 ]; then
    echo "$1 does not exist"
    exit
fi

tmp=$(date +%Y-%m-%d-%H-%M-%S)

natom=$(grep "block = coordinates records" $file|awk '{print $6}')
grep -A$natom "block = coordinates records" $file|tail -n $natom >  ${tmp}_coord
grep -A$natom "block = atom_charges records" $file|tail -n $natom >  ${tmp}_q
netcharge=$(cat ${tmp}_q|awk '{sum+=$1}END{print sum}')
echo $netcharge
multiplicity=$(echo $netcharge|awk '{print $1*2+1}')

echo "xyz $netcharge $multiplicity" >$out

#sed -i "s/[a-zA-Z]+2/Np> /g"

paste ${tmp}_q ${tmp}_coord |awk -v ang=0.52917721092 '{print $2, $1, $3*ang,$4*ang,$5*ang}'>> $out

rm ${tmp}_q ${tmp}_coord 
