#!/bin/env python
#usage: ./converlq.py <lammps data input> <output file name> element1 element2 element3

import numpy as np
import sys

f_in=sys.argv[1]
f_out=sys.argv[2]
name=sys.argv[3:]

lmp=open(f_in,"r")

line=lmp.readline().strip().split()
header=True
while(header):
  if (len(line)>1):
    if (line[0]=='Atoms'):
      header=False
  if (len(line)==2):
    if (line[1] == 'atoms'):
      natom=int(line[0])
  elif (len(line)==3):
    if (line[1] == 'atom' and line[2] == 'types'):
      ntype=int(line[0])
  elif (len(line)==4):
    if (line[2]=='xlo'):
      lx=map(float,line[0:2])
    elif (line[2]=='ylo'):
      ly=map(float,line[0:2])
    elif (line[2]=='zlo'):
      lz=map(float,line[0:2])
  line=lmp.readline().strip().split()

if (len(name) < ntype):
  print "input element names are fewer than the types"
  print "unamed elements will be marked as \'X\'"
  name += ['X']*(ntype-len(name))
alat=lx[1]-lx[0]
cell2=(ly[1]-ly[0])/alat
cell3=(lz[1]-lz[0])/alat

f = open(f_out, 'w')
print >> f, natom, "\n", ntype, "\n",alat,"\n",cell2, "\n",cell3

line_atom=[]
line_type=[]
for i in range(natom):
    line=lmp.readline().strip().split()
    print >> f, name[int(line[1])-1], (float(line[3])-lx[0])/alat, (float(line[4])-ly[0])/alat,(float(line[5])-lz[0])/alat
