a=5.5055
INITIAL="unitcell.lammpstrj"
NX=2 #unit along x direction
NY=2  #unit along z direction
NZ=3
cutline=$(echo $a $NZ|awk '{print $1*$2-$1/2.}')
high=$(echo $a $NZ|awk '{print $1*$2}')
echo $cutline $high

INITIALlmp=${INITIAL//lammpstrj/lmp}
#clean up the file generated by last run
if [ -f $INITIAL ];then
    rm $INITIAL
fi
if [ -f $INITIALlmp ];then
  rm $INITIALlmp
fi

#calculate the bugers vector and generate the unitcell
xx=$(echo "scale=8;$a/sqrt(2)" | bc)
cat >$INITIAL <<EOF 
ITEM: TIMESTEP 
0 
ITEM: NUMBER OF ATOMS 
6 
ITEM: BOX BOUNDS pp pp pp 
0 $xx 
0 $xx 
0 $a 
ITEM: ATOMS id type xs ys zs  
1   1   0.001   0.001   0.25 
2   2   0.001   0.5 0.499
3   2   0.001   0.5 0.001 
4   1   0.5 0.5 0.75 
5   2   0.5 0.999    0.501
6   2   0.5 0.999    0.999
EOF

#100 surface
atomsk_0.8.7 $INITIAL -expand $NX $NY $NZ -cut above  $cutline z unitcell.lmp
zhi=$(awk "NR==8" unitcell.lmp|awk '{print $2+15}')
sed -i 8's/\S\+/'"$zhi"'/2' unitcell.lmp
atomsk_0.8.7 unitcell.lmp -center com POSCAR
mv POSCAR POSCAR100
rm unitcell.lmp

##110 surface
nx=$NX
ny=$(echo $NY|awk '{print $1/2.}')
nz=$(echo $NZ|awk '{print $1*2-1}')
head -n 6 unitcell.lammpstrj >unitcellr.lammpstrj
awk "NR==8" unitcell.lammpstrj >>unitcellr.lammpstrj
awk "NR==7" unitcell.lammpstrj >>unitcellr.lammpstrj
awk "NR==9" unitcell.lammpstrj >>unitcellr.lammpstrj
tail -n 6 unitcell.lammpstrj|awk '{print $1,$2,$3,$5,$4}' >>unitcellr.lammpstrj
atomsk_0.8.7 unitcellr.lammpstrj -expand $nx $ny $nz unitcell.lmp
zhi=$(awk "NR==8" unitcell.lmp|awk '{print $2+15}')
sed -i 8's/\S\+/'"$zhi"'/2' unitcell.lmp
atomsk_0.8.7 unitcell.lmp -center com POSCAR
mv POSCAR POSCAR110
