a=5.52
INITIAL="unitcell.lammpstrj"
NX=3 #unit along x direction
NY=3  #unit along z direction
NZ=10
cutline=$(echo $a $NZ|awk '{print $1*$2-$1/2.}')
high=$(echo $a $NZ|awk '{print $1*$2}')
echo $cutline $high

INITIALlmp=${INITIAL//lammpstrj/lmp}
#clean up the file generated by last run
if [ -f $INITIAL ];then
    rm $INITIAL
fi
if [ -f $INITIALlmp ];then
  rm $INITIALlmp
fi

#calculate the bugers vector and generate the unitcell
xx=$(echo "scale=8;$a/sqrt(2)" | bc)
cat >$INITIAL <<EOF 
ITEM: TIMESTEP 
0 
ITEM: NUMBER OF ATOMS 
6 
ITEM: BOX BOUNDS pp pp pp 
0 $xx 
0 $a
0 $xx
ITEM: ATOMS id type xs ys zs  
1   1   0.0     0.25  0
2   2   0.0     0.5   0.5  
3   2   0.0     0.0   0.5   
4   1   0.5     0.75  0.5  
5   2   0.5     0.5   0
6   2   0.5     0     0
EOF

##110 surface
nx=$NX
ny=$(echo $NY|awk '{print $1/2.}')
nz=$(echo $NZ|awk '{print $1*2-1}')
atomsk_0.8.7 unitcell.lammpstrj -expand $nx $ny $nz unitcell.lmp
#zhi=$(awk "NR==8" unitcell.lmp|awk '{print $2+15}')
#sed -i 8's/\S\+/'"$zhi"'/2' unitcell.lmp
#atomsk_0.8.7 unitcell.lmp -center com POSCAR
#mv POSCAR POSCAR110
