#!/bin/env bash

home=`pwd`

Eh2eV=27.2113834

echo "path E dE nspin | ! 1> headline" >sum
for file in $(find ./ -name "orcaout.*")
do
  nspin="N/A"
  E="N/A"
  dE="N/A"
  line=$(grep "1> !" $file)

  path=$(dirname $file)
  E=$(grep "FINAL SINGLE POINT" $file |tail -n 1|awk -v e=${Eh2eV} '{printf "%.8f\n",$5*e}')
  dE=$(grep "Last Energy change" $file|tail -n 1|awk -v e=${Eh2eV} '{print $5*e}')

  na=$(grep "N(Alpha)"  $file|awk '{print $3}')
  nb=$(grep "N(Beta)"  $file|awk '{print $3}')
  if [ ! $na == "" ]; then
    nspin=$(echo $na $nb|awk '{print $2-$1}')
  fi

  echo $path $E $dE $nspin $line >>sum
done
cat sum
