#!/bin/env bash

home=`pwd`

Eh2eV=27.2113834

echo "path E dE nspin | headline" >sum
for file in $(find ./ -name "orcaout*")  $(find ./ -name "orca1.out")
do
  nspin="N/A"
  E="N/A"
  dE="N/A"
  line=$(grep "1> !" $file|sed "s/|  1> !//g")

  path=$(dirname $file)
  orca_out2json $file $path/hello.json
  if grep -q "FINAL SINGLE POINT" $file; then
    E=$(grep "FINAL SINGLE POINT" $file |tail -n 1|awk -v e=${Eh2eV} '{printf "%.8f\n",$5*e}')
  fi
  if grep -q "Last Energy change" $file; then
    dE=$(grep "Last Energy change" $file|tail -n 1|awk -v e=${Eh2eV} '{print $5*e}')
  fi

  na=$(grep "N(Alpha)"  $file|awk '{print $3}')
  nb=$(grep "N(Beta)"  $file|awk '{print $3}')
  if [ ! $na == "" ]; then
    nspin=$(echo $na $nb|awk '{print $2-$1}')
  fi

  echo $path $E $dE $nspin $line |awk '{printf "%20s %15s %15s %5s",$1,$2,$3,$4; for (i=5;i<=NF;i++) printf " %s", $i; printf "\n"}' >>sum
done
cat sum
